name: Prune unusable items

on:
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: prune
  cancel-in-progress: true

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run prune
        run: python -m scripts.prune
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(prune): remove unusable items and rebuild index"
          branch: main
